# Generated by Django 4.1.6 on 2023-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "website",
                    models.URLField(
                        default="https://www.google.com", verbose_name="Сайт"
                    ),
                ),
                (
                    "message",
                    models.TextField(max_length=5000, verbose_name="Сообщение"),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Создать контакт",
                "verbose_name_plural": "Создать контакты",
                "ordering": ["-create_at"],
            },
        ),
    ]
