# Generated by Django 4.1.6 on 2023-02-04 06:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor.fields.RichTextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="recepi",
            name="direction",
            field=ckeditor.fields.RichTextField(verbose_name="Рецепт"),
        ),
        migrations.AlterField(
            model_name="recepi",
            name="ingridients",
            field=ckeditor.fields.RichTextField(verbose_name="Ингридиенты"),
        ),
    ]
