# Generated by Django 4.1.6 on 2023-02-06 10:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text_present",
            field=ckeditor.fields.RichTextField(
                blank=True, max_length=100, verbose_name="Краткое описание"
            ),
        ),
    ]
