# Generated by Django 4.1.6 on 2023-02-06 10:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_text_present"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text_present",
            field=ckeditor.fields.RichTextField(
                blank=True, max_length=300, verbose_name="Краткое описание"
            ),
        ),
    ]
