# Generated by Django 4.1.6 on 2023-02-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_text_present"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="level",
        ),
        migrations.RemoveField(
            model_name="category",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="category",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="category",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="blank-picture.jpg",
                upload_to="media/%Y/%m/%d/",
                verbose_name="Изображение",
            ),
        ),
    ]
