# Generated by Django 4.1.6 on 2023-02-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_category_level_remove_category_lft_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "verbose_name": "Создать тєг",
                "verbose_name_plural": "Создать тэги",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
